version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  sensor:
    build:
      context: .
      dockerfile: ./components/sensor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq

  controller:
    build:
      context: .
      dockerfile: ./components/controller/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq

  manipulator:
    build:
      context: .
      dockerfile: ./components/manipulator/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq