version: '3'

networks:
  my_network:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  sensor:
    build:
      context: .
      dockerfile: ./components/sensor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    networks:
      - my_network

  controller:
    build:
      context: .
      dockerfile: ./components/controller/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    networks:
      - my_network

  manipulator:
    build:
      context: .
      dockerfile: ./components/manipulator/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    networks:
      - my_network

  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.test
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - sensor
      - controller
      - manipulator
    networks:
      - my_network

