FROM invian_shared

WORKDIR /app

COPY requirements.txt requirements-test.txt ./
RUN pip install -r requirements.txt -r requirements-test.txt

COPY components/ ./components
COPY invian_shared/ ./invian_shared

COPY tests/ ./tests

CMD ["pytest", "./tests"]