# Dockerfile.test
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the components directory contents into the container at /app/components
COPY components/ /app/components/
# Copy the invian_shared directory contents into the container at /app/invian_shared
COPY invian_shared/ /app/invian_shared/
# Copy the tests directory contents into the container at /app/tests
COPY tests/ /app/tests/
# Copy requirements.txt into the container at /app
COPY requirements.txt ./requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Adjust the PYTHONPATH to include the necessary directories
ENV PYTHONPATH "${PYTHONPATH}:/app:/app/invian_shared"

# Run tests.py when the container launches
CMD ["python", "-m", "pytest", "-vv", "/app/tests/"]
